Store the hostname in the volume to catch invocation mismatch.

diff --git a/init-data b/init-data
--- a/init-data
+++ b/init-data
@@ -29,6 +29,16 @@ fi
 DATA=/data
 DATA_TEMPLATE=/data-template
 
+if [ -f "$DATA/hostname" ] ; then
+	STORED_HOSTNAME="$( cat $DATA/hostname )"
+	if [ "$HOSTNAME" != "$STORED_HOSTNAME" ] ; then
+		echo "Invocation error: use -h $STORED_HOSTNAME to match the configured hostname". >&2
+		exit 15
+	fi
+else
+	echo "$HOSTNAME" > "$DATA/hostname"
+fi
+
 if ! [ -f /etc/ipa/ca.crt ] ; then
 	( cd $DATA_TEMPLATE && tar cf - . ) | ( cd $DATA && tar xf - )
 	if [ -n "$PASSWORD" ] || [ -n "$IPA_SERVER_INSTALL_OPTS" ] ; then
